name: Spring Boot CI/CD with MySQL and Redis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DockerAdvanceAssigment

    steps:
      # Checkout the repository
      - name: Check out the repository
        uses: actions/checkout@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Start MySQL, Redis, and Spring Boot application with Docker Compose
      - name: Start Docker Compose
        run: |
          docker compose up -d

      # Wait for MySQL and Redis
      - name: Wait for MySQL and Redis
        run: |
          until docker exec mysql-container mysqladmin ping --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done
          until docker exec redis-container redis-cli ping | grep PONG; do
            echo "Waiting for Redis to be ready..."
            sleep 5
          done

      # Run Tests
      - name: Run Tests
        run: |
          ./mvnw test

      # Check application logs
      - name: Check logs
        run: |
          docker logs spring-boot-app-container

      # Clean up Docker resources
      - name: Clean Up
        if: always()
        run: |
          docker compose down
